package com.lightstick.internal.ble.ota

/**
 * Telink OTA RESULT 통지(0xFF06) 코드 (ResultCode.java 기준).
 *
 * 디바이스가 CMD_OTA_RESULT notification으로 전송.
 * Legacy/Extended 모두 사용, OTA 완료/실패 시 1회만 전송.
 */
internal enum class OtaResultCode(val value: Int, val info: String) {

    OTA_SUCCESS(0x00, "success"),

    OTA_DATA_PACKET_SEQ_ERR(0x01, "OTA data packet sequence number error: repeated OTA PDU or lost some OTA PDU"),
    OTA_PACKET_INVALID(0x02, "invalid OTA packet: 1. invalid OTA command; 2. addr_index out of range; 3. not standard OTA PDU length"),
    OTA_DATA_CRC_ERR(0x03, "packet PDU CRC err"),
    OTA_WRITE_FLASH_ERR(0x04, "write OTA data to flash ERR"),
    OTA_DATA_INCOMPLETE(0x05, "lost last one or more OTA PDU"),
    OTA_FLOW_ERR(0x06, "peer device send OTA command or OTA data not in correct flow"),
    OTA_FW_CHECK_ERR(0x07, "firmware CRC check error"),
    OTA_VERSION_COMPARE_ERR(0x08, "the version number to be updated is lower than the current version"),
    OTA_PDU_LEN_ERR(0x09, "PDU length error: not 16*n, or not equal to value declared in CMD_OTA_START_EXT"),
    OTA_FIRMWARE_MARK_ERR(0x0A, "firmware mark error: not generated by Telink BLE SDK"),
    OTA_FW_SIZE_ERR(0x0B, "firmware size error: no firmware_size; firmware size too small or too big"),
    OTA_DATA_PACKET_TIMEOUT(0x0C, "time interval between two consequent packets exceeded limit"),
    OTA_TIMEOUT(0x0D, "OTA flow total timeout"),
    OTA_FAIL_DUE_TO_CONNECTION_TERMINATE(0x0E, "OTA fail due to connection termination"),

    OTA_SECBOOT_HW_ERR(0x80, "OTA server device hardware error"),
    OTA_SECBOOT_SYSTEM_ERR(0x81, "OTA server device system error"),
    OTA_SECBOOT_FUNC_NOT_ENABLE(0x82, "OTA server device does not enable secure boot"),
    OTA_SECBOOT_PUBKEY_SIGN_SEQ_ERR(0x83, "public key & signature sequence number error"),
    OTA_SECBOOT_PUBKEY_SIGN_LEN_ERR(0x84, "public key & signature data packet length error"),
    OTA_SECBOOT_PUBLIC_KEY_ERR(0x85, "OTA client public key not match server local hash"),
    OTA_SECBOOT_SIGN_VERIFY_FAIL(0x86, "OTA signature verification fail"),
    OTA_SECBOOT_WRITE_DESC_FAIL(0x87, "write secure boot descriptor fail"),
    OTA_SECBOOT_NEW_FW_NOT_MATCH_OLD_FW(0x88, "secure boot: new firmware not match old firmware"),
    OTA_FWENC_NEW_FW_NOT_MATCH_OLD_FW(0x89, "firmware encryption: new firmware not match old firmware"),

    UNKNOWN_CODE(0xFF, "unknown code");

    override fun toString(): String =
        if (this == OTA_SUCCESS) "OTA success"
        else "OTA result: 0x%02X - %s".format(value, info)

    companion object {
        fun from(code: Int): OtaResultCode =
            entries.firstOrNull { it.value == code } ?: UNKNOWN_CODE
    }
}
